#include <string>
using namespace std;
const string MENU = "----------------------------------------------------------------------------\n|0.EXit|1.meNu|2.Multiply|3.Divide|4.Add|5.Subtract|6.SQuareroot|7.Exponent|\n----------------------------------------------------------------------------\n|8.Trigfunctions|9.GEometricsrs+seq|10.Probability|\n---------------------------------------------------\n";
const string VALCALC = "-----------------------------------------\n|Please enter a valid calculator action.|\n-----------------------------------------\n";
const string ACTUALNUM = "-------------------------------\n|Please enter an acutal number|\n-------------------------------\n";
const string WHATELSE = "---------------------------------\n|What else would you like to do?|\n---------------------------------\n";
const string BYE = "----------\n|Goodbye!|\n----------\n";
const string MULTIPLY = "---------------------------------------------------\n|Please enter two numbers to multiply by together.|\n---------------------------------------------------\n";
const string DIVIDE = "-----------------------------------------------------\n|Please enter two numbers to divide by eachother by.|\n-----------------------------------------------------\n";
const string ADD = "-----------------------------------------------\n|Please enter two numbers to add to eachother.|\n-----------------------------------------------\n";
const string SUBTRACT = "------------------------------------------------------\n|Please enter two numbers to subtract from eachother.|\n------------------------------------------------------\n";
const string SQUAREROOT = "--------------------------------------------------\n|Please enter a number to get the square root of.|\n--------------------------------------------------\n";
const string EXPONENT = "-------------------------------------------------\n|Please enter the base First, then the exponent.|\n-------------------------------------------------\n";
const string PROBMENU = "----------------------------\n|0.Back|1.P(A|B)|2.p(aandB)|\n----------------------------\n";
const string PAB = "----------------------------------------\n|Please enter P(AandB) followed by P(B)|\n----------------------------------------\n";
const string PAANDB = "------------------------------------\n|Please enter P(A) followed by P(B)|\n------------------------------------\n";
const string GEOMENU = "------------------------------------------------------\n|0.Back|1.sUmoffinitegsrs|2.Geoseqrule|3.sumofInfgsrs|\n------------------------------------------------------\n";
const string SUMOFFINITE = "---------------------------\n|Please enter R, A1, and N|\n---------------------------\n";
const string GEOSEQRULE = "------------------------------------------------------------\n|Please enter R and An with its subscript sepreated from it|\n------------------------------------------------------------\n";
const string SUMOFINF = "-----------------------\n|Please enter R and A1|\n-----------------------\n";
const string TRIGMENU = "--------------------------\n|0.Back|1.Sin|2.Cos|3.Tan|\n--------------------------\n";
const string RADMES = "-----------------------\n|Please enter a radian|\n-----------------------\n";
const string DEGMES = "-----------------------\n|Please enter a degree|\n-----------------------\n";
const string RADORDEG = "------------------------------------\n|Will this be a radian or a degree?|\n------------------------------------\n";
const string MISSINGNUM = "-------------------------------------------\n|if there is a missing number what is it?|\n-------------------------------------------\n";
